name: action_demo
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: list files
      run: ls -al
    - name: Configure Private Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACTION_DEMO_PRIVATE }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - name: Push changes
      run: |
        # ssh -T git@github.com
        git remote add target git@github.com:hx652/action_prd.git
        git push target master
