name: action_demo
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: list files
      run: ls -al
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ACTION_DEMO_PRIVATE }}

    - name: Push changes
      run: |
        git config --global user.name "Fainic"
        git config --global user.email "Fainic-XD@outlook.com"
        git remote add prd git@github.com:hx652/action_prd.git
        git remote -v
        git push prd master
